package com.kumaru.assistant.core.model

/**
 * Structured persona profile capturing how a user communicates, their preferences,
 * emotional traits, and conversation habits.
 */
data class PersonaProfile(
    val identity: UserIdentity,
    val displayName: String,
    val nickname: String,
    val personalityTraits: List<String>,
    val communicationStyle: String,
    val humorStyle: String,
    val emotionalStyle: String,
    val conversationHabits: List<String>,
    val knownPreferences: List<String>,
    val boundaries: List<String>,
    val responsePreferences: List<String>
)

/**
 * Structured relationship profile between Gowtham and Pavi,
 * capturing shared references, inside jokes, question game patterns, and recurring cadence.
 */
data class RelationshipProfile(
    val sharedReferences: List<String>,
    val recurringJokes: List<String>,
    val sharedActivities: List<String>,
    val conversationPatterns: List<String>,
    val affectionateLanguage: List<String>,
    val questionGamePatterns: List<String>,
    val importantSharedMemories: List<String>
)

/**
 * Unified response model generated by KumaruEngine.
 * Prepares the architecture for future personal voice synthesis and multi-modal feedback.
 */
data class KumaruResponse(
    val text: String,
    val mode: InteractionMode = InteractionMode.CASUAL,
    val toneHint: String = "natural",
    val voiceProfile: String? = null,
    val suggestedFollowUp: String? = null
)
